version: '2'
services:
  nginx:
    image: mritd/nginx
    restart: always
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl
      - /var/log/nginx/:/var/log/nginx/
    volumes_from:
      - piwik_app
    links:
      - jekyll
      - idea
      - rpm
      - minio
      - piwik_app
    ports:
      - "80:80"
      - "443:443"
  jekyll:
    image: mritd/jekyll
    restart: always
  idea:
    image: mritd/idea
    restart: always
  minio:
    image: minio/minio
    restart: always
    volumes:
      - /data/minio:/export
    command: ["server","--address","0.0.0.0:80","/export"]
  rpm:
    image: mritd/rpmrepository
    restart: always
    volumes:
      - /data/repo:/data/repo
  piwik_db:
    image: mysql:5.7.17
    restart: always
    volumes:
      - /data/piwik/mysql/runtime:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
  piwik_app:
    image: mritd/piwik
    restart: always
    links:
      - piwik_db
    volumes:
      - /data/piwik/config:/var/www/html/config
