version: '2'
networks:
  lb_web:
    driver: bridge
  piwik_back:
    driver: bridge
services:
  nginx:
    image: mritd/nginx
    restart: always
    networks:
      - lb_web
      - piwik_back
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl
      - /var/log/nginx/:/var/log/nginx/
    links:
      - jekyll
      - idea
      - rpm
      - minio
      - piwik_app
    ports:
      - "80:80"
      - "443:443"
  jekyll:
    image: mritd/jekyll
    restart: always
    networks:
      - lb_web
  idea:
    image: mritd/idea
    restart: always
    networks:
      - lb_web
  minio:
    image: minio/minio
    restart: always
    networks:
      - lb_web
    volumes:
      - /data/minio:/export
    command: ["server","--address","0.0.0.0:80","/export"]
  rpm:
    image: mritd/rpmrepository
    restart: always
    networks:
      - lb_web
    volumes:
      - /data/repo:/data/repo
  piwik_db:
    image: mysql:5.7.17
    restart: always
    networks:
      - piwik_back
    volumes:
      - /data/piwik/mysql/runtime:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
  piwik_app:
    image: piwik:2.17.1
    restart: always
    networks:
      - piwik_back
    links:
      - piwik_db
    volumes:
      - /data/piwik/config:/var/www/html/config
  piwik_cron:
    image: piwik:2.17.1
    restart: always
    networks:
      - piwik_back
    links:
      - piwik_db
    volumes_from:
      - piwik_app
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        su -s "/bin/bash" -c "/usr/local/bin/php /var/www/html/console core:archive" www-data
        sleep 3600
      done
      EOF'
