version: '2'
services:
  nginx:
    image: mritd/nginx
    restart: always
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl
      - /var/log/nginx/:/var/log/nginx/
    links:
      - jekyll
      - idea
    ports:
      - "80:80"
      - "443:443"
  jekyll:
    image: mritd/jekyll
    restart: always
  idea:
    image: mritd/idea
    restart: always
