version: '2'
networks:
  back:
    driver: bridge
services:
  db:
    image: mysql:5.7.17
    restart: always
    volumes:
      - /data/piwik/mysql/runtime:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
    networks:
      - back
  app:
    image: piwik:2.17.1
    restart: always
    links:
      - db
    volumes:
      - /data/piwik/config:/var/www/html/config
    networks:
      - back
  web:
    image: nginx:1.11.6-alpine
    restart: always
    volumes:
      - /data/piwik/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST
    networks:
      - back
    ports:
      - "127.0.0.1:9000:80"
  cron:
    image: piwik:2.17.1
    restart: always
    links:
      - db
    volumes_from:
      - app
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        su -s "/bin/bash" -c "/usr/local/bin/php /var/www/html/console core:archive" www-data
        sleep 3600
      done
      EOF'
    networks:
      - back
